/**
 * Fetches all 150 Psalms from Sefaria's API and generates src/psalms-data.ts
 * with the full bundled text.
 *
 * Usage: npm run fetch-psalms
 *    or: tsx scripts/fetch-psalms.ts
 */

import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const SEFARIA_BASE = 'https://www.sefaria.org/api/texts';
const TOTAL_PSALMS = 150;
const BATCH_SIZE = 10;
const DELAY_MS = 500;
const RETRY_DELAY_MS = 2000;

interface PsalmEntry {
  he: string[];
  text: string[];
  ref: string;
  heRef: string;
}

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

async function fetchPsalmWithRetry(chapter: number): Promise<PsalmEntry | null> {
  for (let attempt = 0; attempt < 2; attempt++) {
    try {
      const url = `${SEFARIA_BASE}/Psalms.${chapter}`;
      const response = await fetch(url);

      if (!response.ok) {
        throw new Error(`HTTP ${response.status}: ${response.statusText}`);
      }

      const data = await response.json();

      const he: string[] = Array.isArray(data.he) ? data.he : [data.he];
      const text: string[] = Array.isArray(data.text) ? data.text : [data.text];

      return {
        he,
        text,
        ref: data.ref ?? `Psalms ${chapter}`,
        heRef: data.heRef ?? `תהילים ${chapter}`,
      };
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);

      if (attempt === 0) {
        console.warn(`  ⚠ Psalm ${chapter} failed (${message}), retrying in ${RETRY_DELAY_MS}ms...`);
        await sleep(RETRY_DELAY_MS);
      } else {
        console.error(`  ✗ Psalm ${chapter} failed after retry: ${message} — skipping`);
        return null;
      }
    }
  }

  return null;
}

async function main(): Promise<void> {
  console.log(`Fetching all ${TOTAL_PSALMS} Psalms from Sefaria...\n`);

  const psalms: Record<string, PsalmEntry> = {};
  let fetched = 0;
  let skipped = 0;

  for (let batchStart = 1; batchStart <= TOTAL_PSALMS; batchStart += BATCH_SIZE) {
    const batchEnd = Math.min(batchStart + BATCH_SIZE - 1, TOTAL_PSALMS);
    console.log(`Fetching Psalms ${batchStart}-${batchEnd}...`);

    const promises: Promise<{ chapter: number; entry: PsalmEntry | null }>[] = [];

    for (let chapter = batchStart; chapter <= batchEnd; chapter++) {
      promises.push(
        fetchPsalmWithRetry(chapter).then((entry) => ({ chapter, entry })),
      );
    }

    const results = await Promise.all(promises);

    for (const { chapter, entry } of results) {
      if (entry) {
        psalms[String(chapter)] = entry;
        fetched++;
      } else {
        skipped++;
      }
    }

    // Delay between batches (but not after the last one)
    if (batchEnd < TOTAL_PSALMS) {
      await sleep(DELAY_MS);
    }
  }

  // Generate the output file
  const outputPath = join(__dirname, '..', 'src', 'psalms-data.ts');
  const now = new Date().toISOString();

  const lines: string[] = [];
  lines.push('// Auto-generated by scripts/fetch-psalms.ts — do not edit manually');
  lines.push(`// Generated on: ${now}`);
  lines.push('// Source: Sefaria API (https://www.sefaria.org)');
  lines.push('');
  lines.push(
    'export const BUNDLED_PSALMS: Record<string, { he: string[]; text: string[]; ref: string; heRef: string }> = {',
  );

  const chapters = Object.keys(psalms)
    .map(Number)
    .sort((a, b) => a - b);

  for (const chapter of chapters) {
    const entry = psalms[String(chapter)];
    lines.push(`  ${JSON.stringify(String(chapter))}: {`);
    lines.push(`    he: ${JSON.stringify(entry.he)},`);
    lines.push(`    text: ${JSON.stringify(entry.text)},`);
    lines.push(`    ref: ${JSON.stringify(entry.ref)},`);
    lines.push(`    heRef: ${JSON.stringify(entry.heRef)},`);
    lines.push('  },');
  }

  lines.push('};');
  lines.push('');

  writeFileSync(outputPath, lines.join('\n'), 'utf-8');

  console.log(`\nDone! Fetched ${fetched} psalms, skipped ${skipped}.`);
  console.log(`Output written to: ${outputPath}`);
}

main().catch((error) => {
  console.error('Fatal error:', error);
  process.exit(1);
});
